### ISSUE TITLE
Does not work properly

### ISSUE THREAD

**Issue by bh4ll4** [mojipkfr77/InstagramCracker#2]
i used multi threading mode first , it scanned all the passwords very fastly , but did not give the correct password even when i already put the password in the list , when it completed scanning all the passwords , it gave some error and said authentication all false then when i used BASIC MODE , it is very slow one , whats the problem here , and what is basically the difference bw multi threading and basic mode  ,,,,,this is the result which comes when i use MTH mode .......

Authenticated :All False
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 801, in __bootstrap_inner
  File "threading.py", line 754, in run
  File "InstaBrute.py", line 160, in MainRun
NameError: global name 'at' is not defined

**Comment by mojipkfr77** [comment]
i fix the 'thread' problem, you can download the new file and use that.
just make sure , the username that you want to use,  should have phone number or at least email .(Basically, if this is not done, Usename is disabled)
The username that has a "challenge" or any problem can not be cracked.
multi threading is faster than Basic mode

**Comment by bh4ll4** [comment]
sorry , i did not understand by what you said that username should have phone number or email , I am using simple instagram username , is there something different that i have to use ??

**Comment by bh4ll4** [comment]
I tried again but it doesn't work even now , i tried with both the modes but it is not giving me the password , when i already put my password in the password list , there is something wrong with your script

**Comment by mojipkfr77** [comment]
me & my friends are using this script and everything is good , so it hasn't
any problem.
for example you can use "sspkfr77" with pass "789123" for testing.

در تاریخ ۱۱ ژانویهٔ ۲۰۱۸ ۱:۳۶ بعدازظهر، "bh4ll4" <notifications@github.com>
نوشت:

I tried again but it doesn't work even now , i tried with both the modes
but it is not giving me the password , when i already put my password in
the password list , there is something wrong with your script

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/mojipkfr77/InstagramCracker/issues/2#issuecomment-356886711>,
or mute the thread

**Comment by mojipkfr77** [comment]
Username must have "phone number" it means when you are signing in your account , you shouldn't see the "Add Phone Number"  page. so username must verified.

**Comment by bh4ll4** [comment]
i am really in trouble , when i tried with your given ID the script worked correctly , but when i tried with my own ID it didn't worked as expected , my account is also linked to both my email ID and phone number , can you please explain why this is happening ???

**Comment by mojipkfr77** [comment]
dont worry , i changed proxyless method in my new program , i'ill upload new version soon , this issue will be solved .
create another account on instagram and set phone number , try again with this new account and sent me results

**Comment by bh4ll4** [comment]
i am waiting for the updated version but why it is happening so , do you have any idea ??

**Comment by mojipkfr77** [comment]
actually ... no , im confused too. but it will be solve , just wait

**Comment by mojipkfr77** [comment]
Use the new uploaded version. If the account has a "challenge", the program identifies that and stops.

**Comment by bh4ll4** [comment]
sorry to disturb you again but i tried this on three more ID s including mine but the script is neither working for any of the ID , i don't understand where the problem is , when i try on account given by you , it works fine , unable to understand whats the matter ???

**Comment by mojipkfr77** [comment]
look , i told you , if account has "challenge" script cant work, log out &
log in to your account again , you will see the "add phone number page"

**Comment by mojipkfr77** [comment]
try this program , https://github.com/mojipkfr77/InstaBruteForce/
